sudo: required
services: 
  - docker
language: generic

before_install:
  - docker build -t matthewbouchard/multi-container-client -f ./client/Dockerfile.dev ./client
  # could build and consequently test any other dev images and test in these two areas
script:
  - docker run -e CI=true matthewbouchard/multi-container-client npm test

after_success:
  - docker build -t matthewbouchard/mutli-client ./client
  - docker build -t matthewbouchard/mutli-nginx ./nginx
  - docker build -t matthewbouchard/mutli-server ./server
  - docker build -t matthewbouchard/mutli-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take built images and push to dockerhub
  - docker push matthewbouchard/mutli-client
  - docker push matthewbouchard/mutli-nginx
  - docker push matthewbouchard/mutli-server
  - docker push matthewbouchard/mutli-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-453928903836"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
